# Generated by Django 4.2.6 on 2023-11-16 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_order_remove_product_price_remove_product_time_life_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('cpf', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='producer', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Disponível', max_length=50)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='producer',
            name='productions',
            field=models.ManyToManyField(through='producer.Production', to='product.product'),
        ),
    ]
