# Generated by Django 4.2.6 on 2023-11-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.production')),
            ],
        ),
        migrations.AlterField(
            model_name='producer',
            name='productions',
            field=models.ManyToManyField(related_name='productions', through='producer.ProducerProduction', to='producer.production'),
        ),
    ]
