# Generated by Django 4.2.6 on 2023-11-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_remove_product_price_remove_product_time_life_and_more'),
        ('producer', '0002_producerproduction_alter_producer_productions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Aberto', max_length=50)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('expeted_harvest', models.DateField()),
                ('status', models.CharField(default='Em crescimento', max_length=50)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerPlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.planting')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.issue')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer')),
            ],
        ),
        migrations.AddField(
            model_name='producer',
            name='issues',
            field=models.ManyToManyField(related_name='issues', through='producer.ProducerIssue', to='producer.issue'),
        ),
        migrations.AddField(
            model_name='producer',
            name='plantings',
            field=models.ManyToManyField(related_name='plantings', through='producer.ProducerPlanting', to='producer.planting'),
        ),
    ]
