# Generated by Django 4.2.6 on 2023-11-12 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('producer', '0003_alter_producer_address_alter_producer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='type',
            field=models.CharField(default='producer', max_length=50),
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
