# Generated by Django 4.2.6 on 2023-11-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_issue_planting_producerplanting_producerissue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulverization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.CharField(max_length=100)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.planting')),
            ],
        ),
        migrations.CreateModel(
            name='PlantingPulverization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.planting')),
                ('pulverization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.pulverization')),
            ],
        ),
        migrations.AddField(
            model_name='planting',
            name='pulverizations',
            field=models.ManyToManyField(related_name='pulverizations', through='producer.PlantingPulverization', to='producer.pulverization'),
        ),
    ]
