# Generated by Django 4.2.6 on 2023-10-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0008_alter_production_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
