# Generated by Django 4.2.6 on 2023-10-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.FloatField(null=True)),
                ('stock', models.IntegerField(default=0)),
                ('request', models.IntegerField(default=0)),
            ],
        ),
    ]
